services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-pm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /server/nginx/data:/data
      - /server/nginx/letsencrypt:/etc/letsencrypt
    networks:
      nginx_net:
        ipv4_address: 172.18.0.2

networks:
  nginx_net:
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
